# Generated by Django 4.2.6 on 2023-10-27 16:44

import bookstore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='picture',
            field=models.ImageField(null=True, upload_to=bookstore.models.upload_location),
        ),
    ]
