# Generated by Django 4.2.6 on 2023-10-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='provide_haj',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
